version: "3.8"

services:
  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - 80:80
      - 443:443
    volumes_from:
      - wordpress
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - wordpress
 
  wordpress:
    image: wordpress:6.5.0-php8.1-fpm-alpine
    restart: always
    depends_on:
      - database
    environment:
      WORDPRESS_DB_HOST: "database:3306"
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: 1
    volumes:
      - ./docs:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes
 
  database:
    image: yobasystems/alpine-mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql
     
volumes:
  database_data:
    driver: local